
CREATE DATABASE Factusoft;

CREATE TABLE Products(
ID NVARCHAR(3) NOT NULL,
Name NVARCHAR(30) NOT NULL,
UnitValue DECIMAL(10,2) NOT NULL,
UnitMeasure NVARCHAR(3) NOT NULL,
Quantity FLOAT NOT NULL,
IVA DECIMAL(4,1) NOT NULL

);

ALTER TABLE Productos ADD CONSTRAINT PK_Productos_ID PRIMARY KEY CLUSTERED (ID);
